ARG BASE_IMAGE=ubuntu:24.04
FROM ${BASE_IMAGE}

# Install packages
RUN apt-get update && apt-get install -y software-properties-common        

RUN apt-get upgrade -yy

# Install build dependencies for PHP compilation
RUN apt-get install -y \
    build-essential \
    autoconf \
    bison \
    re2c \
    pkg-config \
    libxml2-dev \
    libsqlite3-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    libonig-dev \
    libreadline-dev \
    libbz2-dev \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libwebp-dev \
    libxpm-dev \
    libgd-dev \
    zlib1g-dev \
    libsodium-dev \
    libargon2-dev \
    libicu-dev \
    wget \
    ca-certificates

# Download and extract PHP 8.4.14
WORKDIR /usr/src
RUN wget -q https://www.php.net/distributions/php-8.4.1.tar.gz && \
    tar -xzf php-8.4.1.tar.gz && \
    rm php-8.4.1.tar.gz

# Build PHP 8.4 with all common extensions
WORKDIR /usr/src/php-8.4.1
RUN ./configure \
    --prefix=/usr/local/php8.4 \
    --with-config-file-path=/usr/local/php8.4/etc \
    --with-config-file-scan-dir=/usr/local/php8.4/etc/conf.d \
    --enable-fpm \
    --with-fpm-user=www-data \
    --with-fpm-group=www-data \
    --enable-cli \
    --enable-cgi \
    --enable-bcmath \
    --enable-calendar \
    --enable-exif \
    --enable-ftp \
    --enable-gd \
    --with-external-gd \
    --enable-intl \
    --enable-mbstring \
    --enable-opcache \
    --enable-pcntl \
    --enable-shmop \
    --enable-soap \
    --enable-sockets \
    --enable-sysvmsg \
    --enable-sysvsem \
    --enable-sysvshm \
    --with-bz2 \
    --with-curl \
    --with-openssl \
    --with-readline \
    --with-zip \
    --with-zlib \
    --with-pdo-mysql \
    --with-pdo-sqlite \
    --with-mysqli \
    --with-sodium \
    --with-password-argon2

RUN make -j$(nproc)

# Install PHP
RUN make install

# Install PEAR/PECL
RUN cd /usr/src/php-8.4.1 && \
    wget -q https://pear.php.net/go-pear.phar && \
    /usr/local/php8.4/bin/php go-pear.phar && \
    rm go-pear.phar

# Create symlinks for standard locations
RUN ln -sf /usr/local/php8.4/bin/php /usr/local/bin/php && \
    ln -sf /usr/local/php8.4/bin/php-cgi /usr/local/bin/php-cgi && \
    ln -sf /usr/local/php8.4/bin/php-config /usr/local/bin/php-config && \
    ln -sf /usr/local/php8.4/bin/phpize /usr/local/bin/phpize && \
    ln -sf /usr/local/php8.4/bin/pecl /usr/local/bin/pecl && \
    ln -sf /usr/local/php8.4/bin/pear /usr/local/bin/pear && \
    ln -sf /usr/local/php8.4/sbin/php-fpm /usr/local/bin/php-fpm

# Create PHP-FPM config directories
RUN mkdir -p /usr/local/php8.4/etc/conf.d && \
    mkdir -p /usr/local/php8.4/etc/php-fpm.d && \
    mkdir -p /var/log/php-fpm && \
    mkdir -p /var/run/php

# Copy default configs
RUN cp /usr/src/php-8.4.1/php.ini-production /usr/local/php8.4/etc/php.ini && \
    cp /usr/src/php-8.4.1/sapi/fpm/php-fpm.conf /usr/local/php8.4/etc/php-fpm.conf && \
    cp /usr/src/php-8.4.1/sapi/fpm/www.conf /usr/local/php8.4/etc/php-fpm.d/www.conf

# Configure PHP-FPM to run as www-data
RUN sed -i 's/;pid = run\/php-fpm.pid/pid = \/var\/run\/php\/php8.4-fpm.pid/' /usr/local/php8.4/etc/php-fpm.conf && \
    sed -i 's/;error_log = log\/php-fpm.log/error_log = \/var\/log\/php-fpm\/error.log/' /usr/local/php8.4/etc/php-fpm.conf && \
    sed -i 's/listen = 127.0.0.1:9000/listen = \/var\/run\/php\/php8.4-fpm.sock/' /usr/local/php8.4/etc/php-fpm.d/www.conf && \
    sed -i 's/;listen.owner = www-data/listen.owner = www-data/' /usr/local/php8.4/etc/php-fpm.d/www.conf && \
    sed -i 's/;listen.group = www-data/listen.group = www-data/' /usr/local/php8.4/etc/php-fpm.d/www.conf && \
    sed -i 's/;listen.mode = 0660/listen.mode = 0660/' /usr/local/php8.4/etc/php-fpm.d/www.conf

WORKDIR /