ARG BASE_IMAGE=prep_base:24.04
FROM ${BASE_IMAGE}

RUN apt-get install -y lsb-release ca-certificates apt-transport-https curl
RUN curl -sSLo /tmp/debsuryorg-archive-keyring.deb https://packages.sury.org/debsuryorg-archive-keyring.deb
RUN dpkg -i /tmp/debsuryorg-archive-keyring.deb
RUN sh -c 'echo "deb [signed-by=/usr/share/keyrings/debsuryorg-archive-keyring.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'

# Add PHP PPA
#RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -yy
 
RUN apt-get update && \
        apt-get install -y \
            apache2 \
            php8.4 \
            php8.4-cli \
            php8.4-fpm \
            php8.4-intl \
            php8.4-readline \
            php8.4-bz2 \
            php8.4-common \
            php8.4-gd \
            php8.4-mbstring \
            php8.4-opcache \
            php8.4-cgi \
            php8.4-curl \
            php8.4-mcrypt \
            php8.4-xml

# Enable Apache modules for PHP-FPM
RUN a2enmod proxy_fcgi setenvif rewrite && \
    a2enconf php8.4-fpm

# Create necessary directories
RUN mkdir -p /var/www/html

# Copy apache config
RUN mkdir -p /etc/apache2/sites-enabled; 
COPY src/apache/000-default.conf /etc/apache2/sites-enabled/000-default.conf

# Copy test index.php
COPY src/index.php /var/www/html/index.php
RUN rm /var/www/html/index.html
# Start apache and PHP-FPM
COPY src/docker-entrypoint-apache.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

CMD ["/docker-entrypoint.sh"]
