ARG BASE_IMAGE=prep_nginx:24.04
FROM ${BASE_IMAGE}

# Install imagick via PECL for nginx-based images
# This is done once in the prep image to avoid rebuilding for every variant
RUN apt-get update && \
    apt-get install -y \
        libmagickwand-dev \
        imagemagick \
        build-essential \
        autoconf \
        pkg-config && \
    /usr/local/bin/pecl install imagick && \
    echo "extension=imagick.so" > /usr/local/php8.4/etc/conf.d/20-imagick.ini

