ARG BASE_IMAGE=prep_base:24.04
FROM ${BASE_IMAGE}

# Add PHP PPA
RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -yy
 
RUN apt-get update && \
        apt-get install -y \
            nginx \
            php8.4 \
            php8.4-cli \
            php8.4-fpm \
            php8.4-intl \
            php8.4-readline \
            php8.4-bz2 \
            php8.4-common \
            php8.4-gd \
            php8.4-mbstring \
            php8.4-opcache \
            php8.4-cgi \
            php8.4-curl \
            php8.4-mcrypt \
            php8.4-xml

# Create necessary directories
RUN mkdir -p /var/www/html /run/nginx

# Copy nginx config (with conditional paths for Alpine vs Ubuntu)
RUN mkdir -p /etc/nginx/sites-enabled; 
COPY src/nginx/nginx.conf /etc/nginx/nginx.conf
COPY src/nginx/site.conf /etc/nginx/sites-enabled/nginx.conf

# Copy test index.php
COPY src/index.php /var/www/html/index.php
RUN rm /var/www/html/index.nginx-debian.html
# Start nginx and php-fpm
COPY src/docker-entrypoint-nginx.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

CMD ["/docker-entrypoint.sh"]