ARG BASE_IMAGE=prep_apache2:24.04
FROM ${BASE_IMAGE}

# Install imagick by compiling from source (bypasses pecl which may be
# unavailable after the aggressive prep_base cleanup)
RUN apt-get update && \
    apt-get install -y \
        libmagickwand-dev \
        imagemagick \
        build-essential \
        autoconf \
        pkg-config \
        wget && \
    cd /tmp && \
    wget -q https://pecl.php.net/get/imagick && \
    mkdir imagick-src && tar -xzf imagick -C imagick-src --strip-components=1 && \
    cd imagick-src && \
    /usr/local/bin/phpize && \
    ./configure --with-php-config=/usr/local/bin/php-config && \
    make -j$(nproc) && \
    make install && \
    echo "extension=imagick.so" > /usr/local/php8.4/etc/conf.d/20-imagick.ini && \
    cd / && rm -rf /tmp/imagick-src /tmp/imagick
